# Generated by Django 2.1.1 on 2019-04-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auther_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auther',
            options={'verbose_name_plural': 'ubox--作者'},
        ),
    ]
