# Generated by Django 2.1.1 on 2019-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20190408_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partid', models.CharField(max_length=10, verbose_name='工号')),
                ('partname', models.CharField(max_length=12, verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='Uboxall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('age', models.CharField(max_length=10, verbose_name='年龄')),
                ('part', models.CharField(max_length=10, verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '友宝集团',
            },
        ),
    ]
