# Generated by Django 2.1.1 on 2019-04-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_part_uboxall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Uboxall',
        ),
    ]
