# Generated by Django 2.1.1 on 2019-04-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20190408_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partid', models.CharField(max_length=10, verbose_name='工号')),
            ],
            options={
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='Uboxall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=10, verbose_name='部门名称')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('age', models.CharField(max_length=10, verbose_name='年龄')),
            ],
            options={
                'verbose_name_plural': '友宝集团',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='partinfo',
            field=models.ManyToManyField(related_name='部门详情', to='hello.Uboxall'),
        ),
    ]
