# Generated by Django 2.1.1 on 2019-04-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20190410_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='partinfo',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
